export const ACABADOS_COPY = {
  asignacion: {
    desc: 'Asigne acabados del catálogo a cada plancha configurada en Corte de papel.',
    registro: {
      tag: 'Plancha',
      title: 'Plancha para acabado',
      subtitle: 'Seleccione la plancha con corte de papel configurado para asignar acabados.',
      label: 'Plancha',
      emptySinRegistros: 'Agregue registros en Preprensa y complételos en Corte de papel.',
      placeholder: 'Seleccione una plancha…',
      completo: 'Completado',
      hint: 'Un registro de acabados por plancha. Las planchas completadas se marcan en el listado.',
    },
    planchaDetalle: {
      zoneLabel: 'Datos del corte',
      sectionCorte: 'Corte de papel',
      sectionCorteHint: 'Valores configurados en Corte de papel para la plancha seleccionada.',
      tipoPapelHint: 'Definido en Corte de papel.',
      despieceHint: 'Despiece y medidas del registro seleccionado.',
      tamanosBuenosHint: 'Tamaños buenos del corte aplicados al cálculo de acabados.',
    },
    contexto: {
      tag: 'Contexto',
      title: 'Datos del corte',
      tipoPapel: 'Tipo de papel',
      despiece: 'Despiece por pliego',
      tamanosBuenos: 'Tamaños buenos',
      incompleto: 'Complete tipo de papel, despiece y tamaños buenos en Corte de papel.',
    },
    selector: {
      tag: 'Catálogo',
      title: 'Acabados disponibles',
      quickAccess: 'Acceso rápido',
      quickAccessHint:
        'Los del catálogo con acceso directo en morado. Los elegidos en el select permanecen en violeta claro.',
      allLabel: 'Todos los acabados',
      placeholder: 'Seleccione un acabado…',
      add: 'Agregar acabado',
      duplicate: 'Este acabado ya está asignado a esta plancha.',
      emptyCatalog: 'No hay acabados en el catálogo.',
      planchaCompletaHint:
        'Esta plancha ya tiene acabados confirmados. Use Editar en la tabla para modificarlos.',
    },
    asignados: {
      tag: 'Asignados',
      title: 'Acabados vinculados',
      empty: 'Agregue acabados desde el catálogo o acceso rápido para armar el registro.',
      planchaCompletaHint:
        'No puede agregar más acabados a una plancha completada. Edite el registro existente si necesita cambios.',
      columns: {
        acabado: 'Acabado',
        despiece: 'Despiece',
        valorCmCuadrado: 'Valor cm²',
        tamanosBuenos: 'Tamaños buenos',
        costoMinimo: 'Costo mínimo',
        costoCalculado: 'Costo calculado',
        cobro: 'A cobrar',
        acciones: '',
      },
      crearRegistro: 'Crear registro',
      guardarRegistro: 'Guardar cambios',
      cancelEdit: 'Cancelar edición',
      remove: 'Quitar',
      subtotal: 'Subtotal borrador',
      cobroMinimoHint: 'Aplica costo mínimo',
      formula: {
        summary: 'Ver fórmula de cálculo',
        pasoCostoTitulo: 'Costo calculado',
        pasoCobroTitulo: 'Valor a cobrar',
        pasoTotalTitulo: 'Total a cobrar',
        costoCalculadoRule:
          'Costo calculado = redondeo al entero más cercano de (Ancho ÷ 100) × (Alto ÷ 100) × Valor cm² × Tamaños buenos',
        cobroRule:
          'Si el costo calculado es igual o mayor al costo mínimo del acabado en catálogo, el valor a cobrar es el costo calculado. Si es menor, se cobra el costo mínimo. Ambos valores se redondean al entero más cercano.',
        totalRule:
          'Total a cobrar = suma del valor a cobrar de todos los acabados confirmados',
        hint: 'Ancho y alto provienen del despiece del corte; tamaños buenos del mismo registro.',
      },
    },
    registros: {
      tag: 'Confirmados',
      title: 'Acabados asignados',
      pasoRegistros: 'Acabados asignados',
      emptyTitle: 'Sin acabados asignados',
      empty: 'Agregue acabados arriba y pulse «Crear registro» para confirmarlos aquí.',
      columns: {
        plancha: 'Plancha',
        acabado: 'Acabado',
        acabados: 'Acabados',
        valorCmCuadrado: 'Valor cm²',
        cobro: 'A cobrar',
        total: 'Total registro',
        acciones: 'Acciones',
      },
      edit: 'Editar',
      editing: 'Editando',
      remove: 'Eliminar',
      acabadoSingular: 'acabado',
      acabadoPlural: 'acabados',
      sinAcabados: 'Sin acabados en este registro',
    },
    resumen: {
      tag: 'Resumen',
      title: 'Resumen de acabado',
      totalLabel: 'Total a cobrar',
      totalHint: 'Suma de todos los acabados confirmados por plancha.',
      columns: {
        plancha: 'Plancha',
        cobro: 'A cobrar',
      },
    },
  },
} as const
