export const IMPRESION_COPY = {
  tintas: {
    sectionTags: {
      resumen: 'Resumen',
    },
    panelDesc:
      'Configure un registro de tiro y retiro por cada plancha de Preprensa.',
    registro: {
      tag: 'Plancha',
      title: 'Registro de preprensa',
      subtitle: 'Seleccione la plancha para configurar sus tintas de impresión.',
      label: 'Plancha',
      placeholder: 'Seleccione un registro de preprensa…',
      emptySinRegistros:
        'Aún no hay registros de plancha en Preprensa. Complete Especificaciones técnicas en Preprensa para habilitar esta sección.',
      hint: 'Un solo registro de tintas por plancha. Las planchas completadas se marcan en el listado.',
      completado: 'Completado',
      limiteColores: (total: number, max: number) =>
        `Tiro + retiro: ${total} de ${max} colores de la plancha (deben sumar exactamente ${max}).`,
    },
    planchaDetalle: {
      zoneLabel: 'Datos de impresión',
      sectionPlancha: 'Plancha',
      sectionPlanchaHint: 'Valores del registro de Preprensa seleccionado.',
      sectionVolteo: 'Volteo',
      cavidadesLabel: 'Cavidades',
      cavidadesHint: 'Del registro de Preprensa.',
      cavidadesEmpty: 'Sin cavidades',
      grupoBaseLabel: 'Origen',
      grupoBaseHint: 'Cantidad y cavidades del registro de Preprensa.',
      grupoReferenciaLabel: 'Referencia por tinta',
      grupoReferenciaHint: 'Ajuste para millares según el volteo de cada grupo.',
      tamanosBuenosLabel: 'Tamaños buenos',
      tamanosBuenosHint: 'Calculado desde cantidad y cavidades del registro de Preprensa.',
      tamanosBuenosFormula: 'Cantidad ÷ Cavidades (redondeo al entero más cercano)',
      tamanosBuenosFormulaSummary: 'Ver fórmula de cálculo',
      tamanosBuenosEmpty: '—',
      tamanosBuenosNeedCavidades:
        'Indique las cavidades en Preprensa para calcular los tamaños buenos.',
      tamanosBuenosNeedCantidad:
        'Indique la cantidad en Preprensa para calcular los tamaños buenos.',
      tamanosBuenosReferenciaLabel: 'Tamaños buenos colores básicos',
      tamanosBuenosReferenciaFormulaPatronInicioConVolteo:
        'Inicio: ≤ 600 → 500 · > 600 y ≤ 1.200 → 1.000 · > 1.200 y ≤ 1.600 → 1.500',
      tamanosBuenosReferenciaFormulaPatronContinuaConVolteo:
        'Continúa: alternando rangos de 600 y 400 unidades (+500 por tramo).',
      tamanosBuenosReferenciaFormulaPatronInicioSinVolteo:
        'Inicio: > 0 y ≤ 1.200 → 1.000 · > 1.200 y ≤ 2.200 → 2.000',
      tamanosBuenosReferenciaFormulaPatronContinuaSinVolteo:
        'Continúa: sumando rangos de 1.000 unidades (+1.000 por tramo).',
      tamanosBuenosReferenciaFormulaSummary: 'Ver fórmula de cálculo',
      tamanosBuenosReferenciaEmpty: '—',
      tamanosBuenosPantoneLabel: 'Tamaños buenos pantone',
      tamanosBuenosPantoneFormulaPatronInicioConVolteo:
        'Inicio: ≤ 600 → 500 · > 600 y ≤ 1.200 → 1.000 · > 1.200 y ≤ 1.600 → 1.500',
      tamanosBuenosPantoneFormulaPatronContinuaConVolteo:
        'Continúa: alternando rangos de 600 y 400 unidades (+500 por tramo).',
      tamanosBuenosPantoneFormulaPatronInicioSinVolteo:
        'Inicio: > 0 y ≤ 1.200 → 1.000 · > 1.200 y ≤ 2.200 → 2.000',
      tamanosBuenosPantoneFormulaPatronContinuaSinVolteo:
        'Continúa: sumando rangos de 1.000 unidades (+1.000 por tramo).',
      tamanosBuenosPantoneFormulaSummary: 'Ver fórmula de cálculo',
      tamanosBuenosPantoneEmpty: '—',
      sourceBadge: 'Preprensa',
      impresionConVolteoLabel: 'Impresión con volteo',
      impresionConVolteoHint: 'Active si la plancha se imprime por el reverso con volteo.',
      impresionConVolteoOn: 'Sí',
      impresionConVolteoOff: 'No',
      tipoVolteoLabel: 'Tipo de volteo',
      tipoVolteoPlaceholder: 'Seleccione tipo de volteo…',
      precioMillarLabel: 'Precio por millar',
      unidadMedidaLabel: 'Unidad de medida',
      precioMillarHint: 'Tarifa vigente en Catálogos › Tarifas por millar.',
      precioMillarNoTarifa:
        'Configure el precio de volteo para este grupo.',
      precioMillarEmpty: '—',
      unidadMedidaEmpty: '—',
    },
    diagram: {
      title: 'Vista tiro / retiro',
      empty: 'Asigne tintas para ver el diagrama.',
      inkEmpty: 'Sin tintas asignadas',
      pasadaTiroLabel: '1ª pasada · Tiro',
      pasadaRetiroLabel: '2ª pasada · Retiro',
      resultadoLabel: 'Resultado impreso',
      flipLabel: 'Volteo',
      separateSheets: 'Planchas distintas',
      sinVolteoLabel: 'Sin volteo',
      voltearLabel: 'Voltear',
      volteoPinzaLabel: 'Volteo de pinza',
      volteoEscuadraLabel: 'Volteo de escuadra',
      volteoPinzaRotationHint: 'Rotación sobre el eje de pinza, de tiro a retiro',
      volteoEscuadraRotationHint: 'Rotación sobre el eje de escuadra, de tiro a retiro',
      pinzaLabel: 'pinza',
      pinzaBarLabel: 'PINZA',
      escuadraLabel: 'escuadra',
      escuadraBarLabel: 'ESCUADRA',
      escuadraEscHint: '← ESC',
      legendEscuadra: 'Escuadra — guía lateral (tope en L)',
      legendPinza: 'Pinza — garras de agarre + dirección',
      legendRegistro: 'Marca de registro',
      resultadoTiro: 'Tiro',
      resultadoRetiro: 'Retiro',
      resultadoBifrontalHint: 'Impresión en ambas caras de la hoja',
      faceA: 'cara A',
      faceB: 'cara B',
      faceATiro: 'Cara A · tiro',
      faceBRetiro: 'Cara B · retiro',
      backFace: 'Reverso',
    },
    lado: {
      tiro: 'Tiro',
      tiroHint: 'Tintas en el frente de impresión.',
      retiro: 'Retiro',
      retiroHint: 'Tintas en el reverso.',
      cantidadLabel: 'Cantidad de tintas',
      limiteLado: (max: number, maxPlancha: number) =>
        max <= 0
          ? `No quedan colores disponibles (máximo ${maxPlancha} en la plancha).`
          : `Máximo ${max} tinta${max === 1 ? '' : 's'} en este lado.`,
      tintasTitle: 'Tintas asignadas',
      tintasPrimariosHint:
        'Colores precargados según la cantidad. Puede cambiar cualquier tinta en cualquier momento.',
      tintasAsignacionHint:
        'CMYK y secundarios se precargan según la cantidad. Pantone es un color adicional en el catálogo.',
      slotLabel: (n: number) => `Tinta ${n}`,
      slotPlaceholder: 'Elegir color',
      slotSinAsignar: 'Sin asignar',
      colorPickerTitle: 'Elegir color',
      colorPickerPrimarios: 'Primarios',
      colorPickerSecundarios: 'Secundarios',
      colorPickerPantone: 'Pantone',
    },
    colorBasico: {
      sectionTitle: 'Color básico',
      sectionHint:
        'Tarifa aplicada cuando la plancha tiene todos sus colores asignados y al menos uno es primario o secundario.',
      precioInicialLabel: 'Precio millar sin volteo',
      precioConVolteoLabel: 'Precio con volteo',
      precioPorDefectoLabel: 'Precio con volteo',
      precioMillarLabel: 'Precio millar sin volteo',
      unidadMedidaLabel: 'Unidad de medida',
      topeMinimoMillarLabel: 'Tope mínimo millar',
      millarMinimoVentaLabel: 'Millar mínimo venta',
      umbralDecimalMillarLabel: 'Umbral decimal',
      precioMillarHint: 'Tarifa vigente en Catálogos › Tarifas por millar.',
      precioMillarNoTarifa:
        'Sin tarifa activa de Color básico. Revise el catálogo Tarifas por millar.',
      precioInicialEmpty: '—',
      precioPorDefectoEmpty: '—',
      precioMillarEmpty: '—',
      unidadMedidaEmpty: '—',
      topeMinimoMillarEmpty: '—',
      millarMinimoVentaEmpty: '—',
      umbralDecimalMillarEmpty: '—',
    },
    pantone: {
      sectionTitle: 'Pantone',
      sectionHint:
        'Tarifa aplicada cuando la plancha tiene todos sus colores asignados y al menos uno es Pantone.',
      precioInicialLabel: 'Precio millar sin volteo',
      precioConVolteoLabel: 'Precio con volteo',
      precioPorDefectoLabel: 'Precio con volteo',
      precioMillarLabel: 'Precio millar sin volteo',
      unidadMedidaLabel: 'Unidad de medida',
      topeMinimoMillarLabel: 'Tope mínimo millar',
      millarMinimoVentaLabel: 'Millar mínimo venta',
      umbralDecimalMillarLabel: 'Umbral decimal',
      precioMillarHint: 'Tarifa vigente en Catálogos › Tarifas por millar.',
      precioMillarNoTarifa:
        'Sin tarifa activa de Pantone. Revise el catálogo Tarifas por millar.',
      precioInicialEmpty: '—',
      precioPorDefectoEmpty: '—',
      precioMillarEmpty: '—',
      unidadMedidaEmpty: '—',
      topeMinimoMillarEmpty: '—',
      millarMinimoVentaEmpty: '—',
      umbralDecimalMillarEmpty: '—',
    },
    tintasVolteo: {
      reglasTarifaSummary: 'Reglas de tarifa',
      detalleCalculoSummary: 'Detalle del cálculo',
      volteoStatusSin: 'Sin volteo',
      volteoStatusCon: 'Con volteo',
      volteoModoSin: 'Sin volteo',
      volteoModoCon: 'Con volteo',
      volteoSubtipoLabel: 'Tipo de volteo',
      volteoPinzaShort: 'Pinza',
      volteoEscuadraShort: 'Escuadra',
      colorBasicoHint: 'Configure volteo y tarifa para el grupo de colores básicos.',
      pantoneHint: 'Configure volteo y tarifa para el grupo Pantone.',
      badgeColorBasico: 'Color básico',
      badgePantone: 'Pantone',
      volteoColorBasicoLabel: 'Volteo',
      volteoPantoneLabel: 'Volteo',
      volteoSelectLabel: 'Tipo de impresión',
      volteoSelectHint: 'Elija cómo se imprime el reverso de esta plancha.',
      opcionSinVolteoDesc: 'Tiro y retiro en planchas distintas.',
      opcionConVolteoDesc: 'Misma plancha; elige pinza o escuadra.',
      volteoRequiereCavidadesPares:
        'El volteo solo está disponible cuando las cavidades del registro de Preprensa son un número par.',
      volteoRequiereTiroRetiroColorBasico:
        'El volteo en Color básico requiere colores básicos configurados en tiro y en retiro.',
      volteoRequiereTiroRetiroPantone:
        'El volteo en Pantone requiere colores Pantone configurados en tiro y en retiro.',
      opcionPinzaDesc: 'Se voltea por la pinza.',
      opcionEscuadraDesc: 'Se voltea por la escuadra.',
      volteoSelectPlaceholder: 'Seleccione volteo…',
      tipoVolteoLabel: 'Tipo de volteo',
      volteoOn: 'Sí',
      volteoOff: 'No',
      precioLabel: 'Precio con volteo',
      topeMinimoMillarLabel: 'Tope mínimo millar',
      millarMinimoVentaLabel: 'Millar mínimo venta',
      umbralDecimalMillarLabel: 'Umbral decimal',
      precioEmpty: '—',
      topeMinimoMillarEmpty: '—',
      millarMinimoVentaEmpty: '—',
      umbralDecimalMillarEmpty: '—',
      precioMillarHint: 'Tarifa vigente en Catálogos › Tarifas por millar.',
      precioMillarNoTarifa:
        'Configure el precio de volteo para este grupo.',
    },
    millaresCalculados: {
      label: 'Millares calculados',
      millaresReferenciaLabel: 'Millares referencia',
      millaresInicialLabel: 'Millares referencia',
      empty: '—',
      formulaSummary: 'Ver fórmula de cálculo',
      formulaPasoCalculadosTitulo: 'Millares calculados',
      formulaPasoReferenciaTitulo: 'Millares referencia',
      formulaPasoBaseTitulo: 'Base',
      formulaPasoAjusteTitulo: 'Ajuste',
      baseFormula: '(Tiro + Retiro) × Tamaños buenos colores básicos ÷ 1.000',
      baseFormulaPantone: '(Tiro + Retiro) × Tamaños buenos pantone ÷ 1.000',
      baseFormulaTamanosBuenos: '(Tiro + Retiro) × Tamaños buenos ÷ 1.000',
      referenciaPasoOrigen: 'Parte de millares calculados',
      referenciaPasoTope: 'Comparación con tope mínimo millar',
      referenciaPasoMinimoVenta: 'Millar mínimo venta aplicado',
      referenciaPasoUmbralSiguiente: 'aplica umbral decimal',
      referenciaPasoUmbral: 'Umbral decimal de tarifa',
      referenciaUmbralSinDecimal: 'Sin parte decimal que ajustar',
      referenciaUmbralEnteroSiguiente: 'Parte decimal > {umbral} → entero siguiente',
      referenciaUmbralParteEntera: 'Parte decimal ≤ {umbral} → solo parte entera',
      referenciaPasoAjuste: 'Ajuste aplicado',
      referenciaPasoResultado: 'Millares referencia',
      calculoSectionTitle: 'Resultado del cálculo',
      valorImpresionLabel: 'Precio impresión',
      valorImpresionFormulaSummary: 'Ver cálculo del precio',
      valorImpresionTarifaConVolteo: 'Precio con volteo',
      valorImpresionTarifaSinVolteo: 'Precio sin volteo',
      valorImpresionMotivoRef500: 'ref. 500',
      valorImpresionMotivoRef1000: 'ref. 1.000',
      valorImpresionMotivoVolteoBajoTope: 'bajo tope mínimo',
      valorImpresionMotivoVolteoSobreTope: 'sobre tope mínimo',
      valorImpresionFormulaOperacion: 'Operación',
    },
    entradas: {
      addTitle: 'Nuevo registro tiro / retiro',
      editTitle: 'Editar registro tiro / retiro',
      addHint: 'Configure tiro y retiro, luego agregue el registro de esta plancha.',
      editHint: 'Modifique tiro y retiro y guarde los cambios.',
      addButton: 'Agregar registro',
      saveEdit: 'Guardar cambios',
      cancelEdit: 'Cancelar edición',
      edit: 'Editar',
      editing: 'Editando',
      remove: 'Eliminar',
      empty: 'Configure tiro y retiro arriba, luego pulse «Agregar registro».',
      emptyGlobal:
        'Aún no hay registros. Seleccione una plancha, configure tiro y retiro, y agregue el registro.',
      emptyPlanchaSeleccionada:
        'Esta plancha aún no tiene registro. Configure tiro y retiro arriba y agregue el registro.',
      emptyTitle: 'Sin registros aún',
      registroTintasTitle: 'Tintas por lado',
      registroPreciosTitle: 'Precios de impresión',
      registroTotalLabel: 'Total plancha',
      planchaCompletaHint: 'Esta plancha ya tiene registro. Use Editar en la tabla para modificarlo.',
      yaTieneRegistro: 'Esta plancha ya tiene un registro de tintas.',
      listLabel: 'Registros tiro / retiro de la plancha',
      listTitle: 'Registros agregados',
      resumenLabel: 'Resumen por plancha',
      itemLabel: (n: number) => `Registro ${n}`,
      tablePlancha: 'Plancha',
      tableCantidadColores: 'Cantidad de colores',
      tableTiro: 'Tiro (frente)',
      tableRetiro: 'Retiro (reverso)',
      tableTotal: 'Total tintas',
      tableTintasColorBasico: 'Tintas básicas',
      tableTintasPantone: 'Tintas Pantone',
      tablePrecioColorBasico: 'Precio tinta básico',
      tablePrecioPantone: 'Precio tinta Pantone',
      tintasCountLabel: (n: number) => `${n} tinta${n === 1 ? '' : 's'}`,
      tablePrecioTinta: 'Calcular millares',
      calcularMillaresLabel: 'Calcular millares',
      millaresColorBasicoLabel: 'Color básico',
      millaresPantoneLabel: 'Pantone',
      millaresVolteoLabel: 'Volteo',
      millaresTotalLabel: 'Total millares',
      millaresValueLabel: 'Millares',
      millaresPrecioTintaLabel: 'Precio tinta',
      millaresFormula:
        '(Tiro + retiro) × Tamaños buenos ÷ 1.000 (mínimo 1 millar por grupo si el factor es menor a 1)',
      millaresFormulaColorBasico:
        'Color básico: (tiro + retiro) × Tamaños buenos ÷ 1.000 × Precio Color básico',
      millaresFormulaPantone:
        'Pantone: (tiro + retiro) × Tamaños buenos ÷ 1.000 × Precio Pantone',
      millaresFormulaVolteo:
        'Volteo: millares de Color básico × precio volteo CB; millares de Pantone × precio volteo Pantone',
      tablePrecioVolteo: 'Precio volteo',
      millaresEmpty: '—',
      tableAcciones: 'Acciones',
      ladoSinTintas: 'Sin tintas',
      ladoTintas: (n: number) => `${n} tinta${n === 1 ? '' : 's'}`,
      pasoTiroRetiro: 'Tiro y retiro',
      pasoRegistros: 'Registros',
      registrosCount: (n: number) => (n === 0 ? 'Pendiente' : 'Completado'),
      totalTintas: (total: number, max: number) => `${total} de ${max} tintas`,
      totalValores: (tiro: number, retiro: number) => `${tiro} - ${retiro}`,
      validationError: (max: number) =>
        `La suma de tiro y retiro debe ser exactamente ${max} tintas. Complete todos los colores asignados en cada lado.`,
    },
    miles: {
      title: 'Miles',
      label: 'Miles',
      hint: 'Miles de impresión para el cálculo.',
    },
    resumen: {
      subtitle: (completados: number, total: number) =>
        `${completados} de ${total} plancha${total === 1 ? '' : 's'} con registro de tintas`,
      empty: '—',
      registroIndex: (n: number) => `Plancha ${n}`,
      registroCompletado: 'Completado',
      registroPendiente: 'Pendiente',
      registroEditando: 'Editando esta plancha',
      registroEditandoCorto: 'Editando',
      registroEditar: 'Ir a esta plancha',
      registroEditarHint: 'Pulse para seleccionar y editar',
      precioColorBasico: 'Precio tinta básico',
      precioPantone: 'Precio tinta Pantone',
      precioVolteo: 'Precio volteo',
      totalPlancha: 'Total plancha',
      valorColorBasico: 'Valor tinta básico',
      valorPantone: 'Valor tinta Pantone',
      valorVolteo: 'Valor volteo',
      totalConVolteo: 'Con volteo',
      totalSinVolteo: 'Sin volteo',
      totalVolteoMixto: 'Mixto',
      total: 'Total',
      totalHint: 'Suma de tintas en todas las planchas con registro',
    },
  },
} as const
