export const IMPRESION_COPY = {
  tintas: {
    sectionTags: {
      resumen: 'Resumen',
    },
    panelDesc:
      'Configure un registro de tiro y retiro por cada plancha de Preprensa.',
    registro: {
      tag: 'Plancha',
      title: 'Registro de preprensa',
      subtitle: 'Seleccione la plancha para configurar sus tintas de impresión.',
      label: 'Plancha',
      placeholder: 'Seleccione un registro de preprensa…',
      emptySinRegistros:
        'Aún no hay registros de plancha en Preprensa. Complete Especificaciones técnicas en Preprensa para habilitar esta sección.',
      hint: 'Un solo registro de tintas por plancha. Las planchas completadas se marcan en el listado.',
      completado: 'Completado',
      limiteColores: (total: number, max: number) =>
        `Tiro + retiro: ${total} de ${max} colores de la plancha (deben sumar exactamente ${max}).`,
    },
    planchaDetalle: {
      zoneLabel: 'Datos de impresión',
      sectionPlancha: 'Plancha',
      sectionPlanchaHint: 'Valores del registro de Preprensa seleccionado.',
      sectionVolteo: 'Volteo',
      cavidadesLabel: 'Cavidades',
      cavidadesHint: 'Del registro de Preprensa.',
      cavidadesEmpty: 'Sin cavidades',
      tamanosBuenosLabel: 'Tamaños buenos',
      tamanosBuenosHint: 'Calculado desde cantidad y cavidades del registro de Preprensa.',
      tamanosBuenosFormula: 'Cantidad ÷ Cavidades (redondeo al entero más cercano)',
      tamanosBuenosEmpty: '—',
      tamanosBuenosNeedCavidades:
        'Indique las cavidades en Preprensa para calcular los tamaños buenos.',
      tamanosBuenosNeedCantidad:
        'Indique la cantidad en Preprensa para calcular los tamaños buenos.',
      impresionConVolteoLabel: 'Impresión con volteo',
      impresionConVolteoHint: 'Active si la plancha se imprime por el reverso con volteo.',
      impresionConVolteoOn: 'Sí',
      impresionConVolteoOff: 'No',
      tipoVolteoLabel: 'Tipo de volteo',
      tipoVolteoPlaceholder: 'Seleccione tipo de volteo…',
      precioMillarLabel: 'Precio por millar',
      unidadMedidaLabel: 'Unidad de medida',
      precioMillarHint: 'Tarifa vigente en Catálogos › Tarifas por millar.',
      precioMillarNoTarifa:
        'Sin tarifa activa para este volteo. Revise el catálogo Tarifas por millar.',
      precioMillarEmpty: '—',
      unidadMedidaEmpty: '—',
    },
    lado: {
      tiro: 'Tiro',
      tiroHint: 'Tintas en el frente de impresión.',
      retiro: 'Retiro',
      retiroHint: 'Tintas en el reverso.',
      cantidadLabel: 'Cantidad de tintas',
      limiteLado: (max: number, maxPlancha: number) =>
        max <= 0
          ? `No quedan colores disponibles (máximo ${maxPlancha} en la plancha).`
          : `Máximo ${max} tinta${max === 1 ? '' : 's'} en este lado.`,
      tintasTitle: 'Tintas asignadas',
      tintasPrimariosHint:
        'Colores precargados según la cantidad. Puede cambiar cualquier tinta en cualquier momento.',
      tintasAsignacionHint:
        'CMYK y secundarios se precargan según la cantidad. Pantone es un color adicional en el catálogo.',
      slotLabel: (n: number) => `Tinta ${n}`,
      slotPlaceholder: 'Elegir color',
      slotSinAsignar: 'Sin asignar',
      colorPickerTitle: 'Elegir color',
      colorPickerPrimarios: 'Primarios',
      colorPickerSecundarios: 'Secundarios',
      colorPickerPantone: 'Pantone',
    },
    colorBasico: {
      sectionTitle: 'Color básico',
      sectionHint:
        'Tarifa aplicada cuando la plancha tiene todos sus colores asignados y al menos uno es primario o secundario.',
      precioMillarLabel: 'Precio por millar',
      unidadMedidaLabel: 'Unidad de medida',
      precioMillarHint: 'Tarifa vigente en Catálogos › Tarifas por millar.',
      precioMillarNoTarifa:
        'Sin tarifa activa de Color básico. Revise el catálogo Tarifas por millar.',
      precioMillarEmpty: '—',
      unidadMedidaEmpty: '—',
    },
    pantone: {
      sectionTitle: 'Pantone',
      sectionHint:
        'Tarifa aplicada cuando la plancha tiene todos sus colores asignados y al menos uno es Pantone.',
      precioMillarLabel: 'Precio por millar',
      unidadMedidaLabel: 'Unidad de medida',
      precioMillarHint: 'Tarifa vigente en Catálogos › Tarifas por millar.',
      precioMillarNoTarifa:
        'Sin tarifa activa de Pantone. Revise el catálogo Tarifas por millar.',
      precioMillarEmpty: '—',
      unidadMedidaEmpty: '—',
    },
    entradas: {
      addTitle: 'Nuevo registro tiro / retiro',
      editTitle: 'Editar registro tiro / retiro',
      addHint: 'Configure tiro y retiro, luego agregue el registro de esta plancha.',
      editHint: 'Modifique tiro y retiro y guarde los cambios.',
      addButton: 'Agregar registro',
      saveEdit: 'Guardar cambios',
      cancelEdit: 'Cancelar edición',
      edit: 'Editar',
      editing: 'Editando',
      remove: 'Eliminar',
      empty: 'Configure tiro y retiro arriba, luego pulse «Agregar registro».',
      emptyGlobal:
        'Aún no hay registros. Seleccione una plancha, configure tiro y retiro, y agregue el registro.',
      emptyTitle: 'Sin registros aún',
      planchaCompletaHint: 'Esta plancha ya tiene registro. Use Editar en la tabla para modificarlo.',
      yaTieneRegistro: 'Esta plancha ya tiene un registro de tintas.',
      listLabel: 'Registros tiro / retiro de la plancha',
      listTitle: 'Registros agregados',
      resumenLabel: 'Resumen por plancha',
      itemLabel: (n: number) => `Registro ${n}`,
      tablePlancha: 'Plancha',
      tableCantidadColores: 'Cantidad de colores',
      tableTiro: 'Tiro (frente)',
      tableRetiro: 'Retiro (reverso)',
      tableTotal: 'Total tintas',
      tableTintasColorBasico: 'Tintas básicas',
      tableTintasPantone: 'Tintas Pantone',
      tablePrecioColorBasico: 'Precio tinta básico',
      tablePrecioPantone: 'Precio tinta Pantone',
      tintasCountLabel: (n: number) => `${n} tinta${n === 1 ? '' : 's'}`,
      tablePrecioTinta: 'Calcular millares',
      calcularMillaresLabel: 'Calcular millares',
      millaresColorBasicoLabel: 'Color básico',
      millaresPantoneLabel: 'Pantone',
      millaresVolteoLabel: 'Volteo',
      millaresTotalLabel: 'Total millares',
      millaresValueLabel: 'Millares',
      millaresPrecioTintaLabel: 'Precio tinta',
      millaresFormula:
        '(Tiro + retiro) × Tamaños buenos ÷ 1.000 (mínimo 1 millar por grupo si el factor es menor a 1)',
      millaresFormulaColorBasico:
        'Color básico: (tiro + retiro) × Tamaños buenos ÷ 1.000 × Precio Color básico',
      millaresFormulaPantone:
        'Pantone: (tiro + retiro) × Tamaños buenos ÷ 1.000 × Precio Pantone',
      millaresFormulaVolteo:
        'Volteo: Millares del registro tiro/retiro × Precio por millar del tipo de volteo',
      tablePrecioVolteo: 'Precio volteo',
      millaresEmpty: '—',
      tableAcciones: 'Acciones',
      ladoSinTintas: 'Sin tintas',
      ladoTintas: (n: number) => `${n} tinta${n === 1 ? '' : 's'}`,
      pasoTiroRetiro: 'Tiro y retiro',
      pasoRegistros: 'Registros',
      registrosCount: (n: number) => (n === 0 ? 'Pendiente' : 'Completado'),
      totalTintas: (total: number, max: number) => `${total} de ${max} tintas`,
      totalValores: (tiro: number, retiro: number) => `${tiro} - ${retiro}`,
      validationError: (max: number) =>
        `La suma de tiro y retiro debe ser exactamente ${max} tintas. Complete todos los colores asignados en cada lado.`,
    },
    miles: {
      title: 'Miles',
      label: 'Miles',
      hint: 'Miles de impresión para el cálculo.',
    },
    resumen: {
      title: 'Resumen de tintas',
      subtitle: (completados: number, total: number) =>
        `${completados} de ${total} plancha${total === 1 ? '' : 's'} con registro de tintas`,
      empty: '—',
      registroIndex: (n: number) => `Plancha ${n}`,
      registroCompletado: 'Completado',
      registroPendiente: 'Pendiente',
      registroEditando: 'Editando esta plancha',
      registroEditandoCorto: 'Editando',
      registroEditar: 'Ir a esta plancha',
      registroEditarHint: 'Pulse para seleccionar y editar',
      precioColorBasico: 'Precio tinta básico',
      precioPantone: 'Precio tinta Pantone',
      precioVolteo: 'Precio volteo',
      totalPlancha: 'Total plancha',
      totalColorBasico: 'Total tinta básico',
      totalPantone: 'Total tinta Pantone',
      totalVolteo: 'Total volteo',
      totalLabel: 'Total a cobrar',
      totalHint: 'Suma de tintas y volteo en todas las planchas con registro',
    },
  },
} as const
