export const IMPRESION_COPY = {
  tintas: {
    sectionTags: {
      resumen: 'Resumen',
    },
    panelDesc:
      'Configure un registro de tiro y retiro por cada plancha de Preprensa.',
    registro: {
      tag: 'Plancha',
      title: 'Registro de preprensa',
      subtitle: 'Seleccione la plancha para configurar sus tintas de impresión.',
      label: 'Plancha',
      placeholder: 'Seleccione un registro de preprensa…',
      emptySinRegistros:
        'Aún no hay registros de plancha en Preprensa. Complete Especificaciones técnicas en Preprensa para habilitar esta sección.',
      hint: 'Un solo registro de tintas por plancha. Las planchas completadas se marcan en el listado.',
      completado: 'Completado',
      limiteColores: (total: number, max: number) =>
        `Tiro + retiro: ${total} de ${max} colores de la plancha (deben sumar exactamente ${max}).`,
    },
    planchaDetalle: {
      zoneLabel: 'Datos de impresión',
      sectionPlancha: 'Plancha',
      sectionPlanchaHint: 'Valores del registro de Preprensa seleccionado.',
      sectionVolteo: 'Volteo',
      cavidadesLabel: 'Cavidades',
      cavidadesHint: 'Del registro de Preprensa.',
      cavidadesEmpty: 'Sin cavidades',
      grupoBaseLabel: 'Origen',
      grupoBaseHint: 'Cantidad y cavidades del registro de Preprensa.',
      grupoReferenciaLabel: 'Referencia por tinta',
      grupoReferenciaHint: 'Ajuste para millares según el volteo de cada grupo.',
      tamanosBuenosLabel: 'Tamaños buenos',
      tamanosBuenosHint: 'Calculado desde cantidad y cavidades del registro de Preprensa.',
      tamanosBuenosFormula: 'Cantidad ÷ Cavidades (redondeo al entero más cercano)',
      tamanosBuenosFormulaSummary: 'Ver fórmula de cálculo',
      tamanosBuenosEmpty: '—',
      tamanosBuenosNeedCavidades:
        'Indique las cavidades en Preprensa para calcular los tamaños buenos.',
      tamanosBuenosNeedCantidad:
        'Indique la cantidad en Preprensa para calcular los tamaños buenos.',
      tamanosBuenosReferenciaLabel: 'Tamaños buenos colores básicos',
      tamanosBuenosReferenciaFormulaPatronInicioConVolteo:
        'Inicio: ≤ 600 → 500 · > 600 y ≤ 1.200 → 1.000 · > 1.200 y ≤ 1.600 → 1.500',
      tamanosBuenosReferenciaFormulaPatronContinuaConVolteo:
        'Continúa: alternando rangos de 600 y 400 unidades (+500 por tramo).',
      tamanosBuenosReferenciaFormulaPatronInicioSinVolteo:
        'Inicio: > 0 y ≤ 1.200 → 1.000 · > 1.200 y ≤ 2.200 → 2.000',
      tamanosBuenosReferenciaFormulaPatronContinuaSinVolteo:
        'Continúa: sumando rangos de 1.000 unidades (+1.000 por tramo).',
      tamanosBuenosReferenciaFormulaSummary: 'Ver fórmula de cálculo',
      tamanosBuenosReferenciaEmpty: '—',
      tamanosBuenosPantoneLabel: 'Tamaños buenos pantone',
      tamanosBuenosPantoneFormulaPatronInicioConVolteo:
        'Inicio: ≤ 600 → 500 · > 600 y ≤ 1.200 → 1.000 · > 1.200 y ≤ 1.600 → 1.500',
      tamanosBuenosPantoneFormulaPatronContinuaConVolteo:
        'Continúa: alternando rangos de 600 y 400 unidades (+500 por tramo).',
      tamanosBuenosPantoneFormulaPatronInicioSinVolteo:
        'Inicio: > 0 y ≤ 1.200 → 1.000 · > 1.200 y ≤ 2.200 → 2.000',
      tamanosBuenosPantoneFormulaPatronContinuaSinVolteo:
        'Continúa: sumando rangos de 1.000 unidades (+1.000 por tramo).',
      tamanosBuenosPantoneFormulaSummary: 'Ver fórmula de cálculo',
      tamanosBuenosPantoneEmpty: '—',
      sourceBadge: 'Preprensa',
      impresionConVolteoLabel: 'Impresión con volteo',
      impresionConVolteoHint: 'Active si la plancha se imprime por el reverso con volteo.',
      impresionConVolteoOn: 'Sí',
      impresionConVolteoOff: 'No',
      tipoVolteoLabel: 'Tipo de volteo',
      tipoVolteoPlaceholder: 'Seleccione tipo de volteo…',
      precioMillarLabel: 'Precio por millar',
      unidadMedidaLabel: 'Unidad de medida',
      precioMillarHint: 'Tarifa vigente en Catálogos › Tarifas por millar.',
      precioMillarNoTarifa:
        'Configure el precio de volteo para este grupo.',
      precioMillarEmpty: '—',
      unidadMedidaEmpty: '—',
    },
    pruebaContrato: {
      tag: 'Contrato',
      zoneLabel: 'Prueba de contrato',
      subtitle: 'Indique quién suministra la Prueba Sherpa para esta plancha.',
      ariaLabel: 'Quién suministra la Prueba Sherpa',
      cobroLabel: 'Valor a cobrar (COP)',
      opciones: {
        cliente: {
          title: 'Cliente suministra Prueba Sherpa',
          description: 'El cliente entrega la prueba; no aplica cobro',
        },
        empresa: {
          title: 'Litografía suministra Prueba Sherpa',
          description: 'La empresa provee la prueba y puede cobrarla al cliente',
        },
      },
    },
    diagram: {
      title: 'Vista tiro / retiro',
      empty: 'Asigne tintas para ver el diagrama.',
      inkEmpty: 'Sin tintas asignadas',
      pasadaTiroLabel: '1ª pasada · Tiro',
      pasadaRetiroLabel: '2ª pasada · Retiro',
      resultadoLabel: 'Resultado impreso',
      flipLabel: 'Volteo',
      separateSheets: 'Planchas distintas',
      sinVolteoLabel: 'Sin volteo',
      voltearLabel: 'Voltear',
      volteoPinzaLabel: 'Volteo de pinza',
      volteoEscuadraLabel: 'Volteo de escuadra',
      volteoPinzaRotationHint: 'Rotación sobre el eje de pinza, de tiro a retiro',
      volteoEscuadraRotationHint: 'Rotación sobre el eje de escuadra, de tiro a retiro',
      pinzaLabel: 'pinza',
      pinzaBarLabel: 'PINZA',
      escuadraLabel: 'escuadra',
      escuadraBarLabel: 'ESCUADRA',
      escuadraEscHint: '← ESC',
      legendEscuadra: 'Escuadra — guía lateral (tope en L)',
      legendPinza: 'Pinza — garras de agarre + dirección',
      legendRegistro: 'Marca de registro',
      resultadoTiro: 'Tiro',
      resultadoRetiro: 'Retiro',
      resultadoBifrontalHint: 'Impresión en ambas caras de la hoja',
      faceA: 'cara A',
      faceB: 'cara B',
      faceATiro: 'Cara A · tiro',
      faceBRetiro: 'Cara B · retiro',
      backFace: 'Reverso',
    },
    lado: {
      tiro: 'Tiro',
      tiroHint: 'Tintas en el frente de impresión.',
      retiro: 'Retiro',
      retiroHint: 'Tintas en el reverso.',
      cantidadLabel: 'Cantidad de tintas',
      limiteLado: (max: number, maxPlancha: number) =>
        max <= 0
          ? `No quedan colores disponibles (máximo ${maxPlancha} en la plancha).`
          : `Máximo ${max} tinta${max === 1 ? '' : 's'} en este lado.`,
      tintasTitle: 'Tintas asignadas',
      tintasPrimariosHint:
        'Colores precargados según la cantidad. Puede cambiar cualquier tinta en cualquier momento.',
      tintasAsignacionHint:
        'CMYK y secundarios se precargan según la cantidad. Pantone es un color adicional en el catálogo.',
      slotLabel: (n: number) => `Tinta ${n}`,
      slotPlaceholder: 'Elegir color',
      slotSinAsignar: 'Sin asignar',
      colorPickerTitle: 'Elegir color',
      colorPickerPrimarios: 'Primarios',
      colorPickerSecundarios: 'Secundarios',
      colorPickerPantone: 'Pantone',
    },
    colorBasico: {
      sectionTitle: 'Color básico',
      sectionHint:
        'Tarifa aplicada cuando la plancha tiene todos sus colores asignados y al menos uno es primario o secundario.',
      precioInicialLabel: 'Precio millar sin volteo',
      precioConVolteoLabel: 'Precio con volteo',
      precioPorDefectoLabel: 'Precio con volteo',
      precioMillarLabel: 'Precio millar sin volteo',
      unidadMedidaLabel: 'Unidad de medida',
      topeMinimoMillarLabel: 'Tope mínimo millar',
      millarMinimoVentaLabel: 'Millar mínimo venta',
      umbralDecimalMillarLabel: 'Umbral decimal',
      precioMillarHint: 'Tarifa vigente en Catálogos › Tarifas por millar.',
      precioMillarNoTarifa:
        'Sin tarifa activa de Color básico. Revise el catálogo Tarifas por millar.',
      precioInicialEmpty: '—',
      precioPorDefectoEmpty: '—',
      precioMillarEmpty: '—',
      unidadMedidaEmpty: '—',
      topeMinimoMillarEmpty: '—',
      millarMinimoVentaEmpty: '—',
      umbralDecimalMillarEmpty: '—',
    },
    pantone: {
      sectionTitle: 'Pantone',
      sectionHint:
        'Tarifa aplicada cuando la plancha tiene todos sus colores asignados y al menos uno es Pantone.',
      precioInicialLabel: 'Precio millar sin volteo',
      precioConVolteoLabel: 'Precio con volteo',
      precioPorDefectoLabel: 'Precio con volteo',
      precioMillarLabel: 'Precio millar sin volteo',
      unidadMedidaLabel: 'Unidad de medida',
      topeMinimoMillarLabel: 'Tope mínimo millar',
      millarMinimoVentaLabel: 'Millar mínimo venta',
      umbralDecimalMillarLabel: 'Umbral decimal',
      precioMillarHint: 'Tarifa vigente en Catálogos › Tarifas por millar.',
      precioMillarNoTarifa:
        'Sin tarifa activa de Pantone. Revise el catálogo Tarifas por millar.',
      precioInicialEmpty: '—',
      precioPorDefectoEmpty: '—',
      precioMillarEmpty: '—',
      unidadMedidaEmpty: '—',
      topeMinimoMillarEmpty: '—',
      millarMinimoVentaEmpty: '—',
      umbralDecimalMillarEmpty: '—',
    },
    tintaPantoneSuministro: {
      label: 'Tinta Pantone',
      ariaLabel: 'Quién suministra la tinta Pantone',
      opcionCliente: 'Cliente',
      opcionLitografia: 'Litografía',
      cobroLabel: 'Cobro',
      precioDisplayLabel: 'Precio tinta Pantone',
    },
    tintasVolteo: {
      reglasTarifaSummary: 'Reglas de tarifa',
      detalleCalculoSummary: 'Detalle del cálculo',
      volteoStatusSin: 'Sin volteo',
      volteoStatusCon: 'Con volteo',
      volteoModoSin: 'Sin volteo',
      volteoModoCon: 'Con volteo',
      volteoSubtipoLabel: 'Tipo de volteo',
      volteoPinzaShort: 'Pinza',
      volteoEscuadraShort: 'Escuadra',
      colorBasicoHint: 'Configure volteo y tarifa para el grupo de colores básicos.',
      pantoneHint: 'Configure volteo y tarifa para el grupo Pantone.',
      badgeColorBasico: 'Color básico',
      badgePantone: 'Pantone',
      volteoColorBasicoLabel: 'Volteo',
      volteoPantoneLabel: 'Volteo',
      volteoSelectLabel: 'Tipo de impresión',
      volteoSelectHint: 'Elija cómo se imprime el reverso de esta plancha.',
      opcionSinVolteoDesc: 'Tiro y retiro en planchas distintas.',
      opcionConVolteoDesc: 'Misma plancha; elige pinza o escuadra.',
      volteoRequiereCavidadesPares:
        'El volteo solo está disponible cuando las cavidades del registro de Preprensa son un número par.',
      volteoRequiereTiroRetiroColorBasico:
        'El volteo en Color básico requiere colores básicos configurados en tiro y en retiro.',
      volteoRequiereTiroRetiroPantone:
        'El volteo en Pantone requiere colores Pantone configurados en tiro y en retiro.',
      opcionPinzaDesc: 'Se voltea por la pinza.',
      opcionEscuadraDesc: 'Se voltea por la escuadra.',
      volteoSelectPlaceholder: 'Seleccione volteo…',
      tipoVolteoLabel: 'Tipo de volteo',
      volteoOn: 'Sí',
      volteoOff: 'No',
      precioLabel: 'Precio con volteo',
      topeMinimoMillarLabel: 'Tope mínimo millar',
      millarMinimoVentaLabel: 'Millar mínimo venta',
      umbralDecimalMillarLabel: 'Umbral decimal',
      precioEmpty: '—',
      topeMinimoMillarEmpty: '—',
      millarMinimoVentaEmpty: '—',
      umbralDecimalMillarEmpty: '—',
      precioMillarHint: 'Tarifa vigente en Catálogos › Tarifas por millar.',
      precioMillarNoTarifa:
        'Configure el precio de volteo para este grupo.',
    },
    millaresCalculados: {
      label: 'Millares calculados',
      millaresReferenciaLabel: 'Millares referencia',
      millaresInicialLabel: 'Millares referencia',
      empty: '—',
      formulaSummary: 'Ver fórmula de cálculo',
      formulaPasoCalculadosTitulo: 'Millares calculados',
      formulaPasoReferenciaTitulo: 'Millares referencia',
      formulaPasoBaseTitulo: 'Base',
      formulaPasoAjusteTitulo: 'Ajuste',
      baseFormula: '(Tiro + Retiro) × Tamaños buenos colores básicos ÷ 1.000',
      baseFormulaPantone: '(Tiro + Retiro) × Tamaños buenos pantone ÷ 1.000',
      baseFormulaTamanosBuenos: '(Tiro + Retiro) × Tamaños buenos ÷ 1.000',
      referenciaPasoOrigen: 'Parte de millares calculados',
      referenciaPasoTope: 'Comparación con tope mínimo millar',
      referenciaPasoMinimoVenta: 'Millar mínimo venta aplicado',
      referenciaPasoUmbralSiguiente: 'aplica umbral decimal',
      referenciaPasoUmbral: 'Umbral decimal de tarifa',
      referenciaUmbralSinDecimal: 'Sin parte decimal que ajustar',
      referenciaUmbralEnteroSiguiente: 'Parte decimal > {umbral} → entero siguiente',
      referenciaUmbralParteEntera: 'Parte decimal ≤ {umbral} → solo parte entera',
      referenciaPasoAjuste: 'Ajuste aplicado',
      referenciaPasoResultado: 'Millares referencia',
      calculoSectionTitle: 'Resultado del cálculo',
      valorImpresionLabel: 'Precio impresión',
      valorImpresionFormulaSummary: 'Ver cálculo del precio',
      valorImpresionTarifaConVolteo: 'Precio con volteo',
      valorImpresionTarifaSinVolteo: 'Precio sin volteo',
      valorImpresionMotivoRef500: 'ref. 500',
      valorImpresionMotivoRef1000: 'ref. 1.000',
      valorImpresionMotivoVolteoBajoTope: 'bajo tope mínimo',
      valorImpresionMotivoVolteoSobreTope: 'sobre tope mínimo',
      valorImpresionFormulaOperacion: 'Operación',
    },
    entradas: {
      addTitle: 'Nuevo registro tiro / retiro',
      editTitle: 'Editar registro tiro / retiro',
      addHint: 'Configure tiro y retiro, luego agregue el registro de esta plancha.',
      editHint: 'Modifique tiro y retiro y guarde los cambios.',
      addButton: 'Agregar registro',
      saveEdit: 'Guardar cambios',
      cancelEdit: 'Cancelar edición',
      edit: 'Editar',
      editing: 'Editando',
      remove: 'Eliminar',
      empty: 'Configure tiro y retiro arriba, luego pulse «Agregar registro».',
      emptyGlobal:
        'Aún no hay registros. Seleccione una plancha, configure tiro y retiro, y agregue el registro.',
      emptyPlanchaSeleccionada:
        'Esta plancha aún no tiene registro. Configure tiro y retiro arriba y agregue el registro.',
      emptyTitle: 'Sin registros aún',
      registroTintasTitle: 'Tintas por lado',
      registroPreciosTitle: 'Precios de impresión',
      registroTotalLabel: 'Total plancha',
      planchaCompletaHint: 'Esta plancha ya tiene registro. Use Editar en la tabla para modificarlo.',
      yaTieneRegistro: 'Esta plancha ya tiene un registro de tintas.',
      listLabel: 'Registros tiro / retiro de la plancha',
      listTitle: 'Registros agregados',
      resumenLabel: 'Resumen por plancha',
      itemLabel: (n: number) => `Registro ${n}`,
      tablePlancha: 'Plancha',
      tableCantidadColores: 'Cantidad de colores',
      tableTiro: 'Tiro (frente)',
      tableRetiro: 'Retiro (reverso)',
      tableTotal: 'Total tintas',
      tableTintasColorBasico: 'Tintas básicas',
      tableTintasPantone: 'Impresión Pantone',
      tablePrecioColorBasico: 'Precio tinta básico',
      tablePrecioImpresionPantone: 'Precio impresión Pantone',
      tablePrecioPantone: 'Precio tinta Pantone',
      tintasCountLabel: (n: number) => `${n} tinta${n === 1 ? '' : 's'}`,
      tablePrecioTinta: 'Calcular millares',
      calcularMillaresLabel: 'Calcular millares',
      millaresColorBasicoLabel: 'Color básico',
      millaresPantoneLabel: 'Pantone',
      millaresVolteoLabel: 'Volteo',
      millaresTotalLabel: 'Total millares',
      millaresValueLabel: 'Millares',
      millaresPrecioTintaLabel: 'Precio tinta',
      millaresFormula:
        '(Tiro + retiro) × Tamaños buenos ÷ 1.000 (mínimo 1 millar por grupo si el factor es menor a 1)',
      millaresFormulaColorBasico:
        'Color básico: (tiro + retiro) × Tamaños buenos ÷ 1.000 × Precio Color básico',
      millaresFormulaPantone:
        'Pantone: (tiro + retiro) × Tamaños buenos ÷ 1.000 × Precio Pantone',
      millaresFormulaVolteo:
        'Volteo: millares de Color básico × precio volteo CB; millares de Pantone × precio volteo Pantone',
      tablePrecioVolteo: 'Precio volteo',
      millaresEmpty: '—',
      tableAcciones: 'Acciones',
      ladoSinTintas: 'Sin tintas',
      ladoTintas: (n: number) => `${n} tinta${n === 1 ? '' : 's'}`,
      pasoTiroRetiro: 'Tiro y retiro',
      pasoRegistros: 'Registros',
      registrosCount: (n: number) => (n === 0 ? 'Pendiente' : 'Completado'),
      totalTintas: (total: number, max: number) => `${total} de ${max} tintas`,
      totalValores: (tiro: number, retiro: number) => `${tiro} - ${retiro}`,
      validationError: (max: number) =>
        `La suma de tiro y retiro debe ser exactamente ${max} tintas. Complete todos los colores asignados en cada lado.`,
    },
    miles: {
      title: 'Miles',
      label: 'Miles',
      hint: 'Miles de impresión para el cálculo.',
    },
    resumen: {
      subtitle: (completados: number, total: number) =>
        `${completados} de ${total} plancha${total === 1 ? '' : 's'} con registro de tintas`,
      empty: '—',
      registroIndex: (n: number) => `Plancha ${n}`,
      registroCompletado: 'Completado',
      registroPendiente: 'Pendiente',
      registroEditando: 'Editando esta plancha',
      registroEditandoCorto: 'Editando',
      registroEditar: 'Ir a esta plancha',
      registroEditarHint: 'Pulse para seleccionar y editar',
      precioColorBasico: 'Precio tinta básico',
      precioPantone: 'Precio tinta Pantone',
      precioVolteo: 'Precio volteo',
      totalPlancha: 'Total plancha',
      valorColorBasico: 'Valor tinta básico',
      valorPantone: 'Valor impresión Pantone',
      valorCobroTintaPantone: 'Valor tinta Pantone',
      valorVolteo: 'Valor volteo',
      totalConVolteo: 'Con volteo',
      totalSinVolteo: 'Sin volteo',
      totalVolteoMixto: 'Mixto',
      total: 'Total',
      totalHint: 'Suma de tintas en todas las planchas con registro',
      valorPruebaSherpa: 'Valor prueba Sherpa',
    },
  },
  muestra: {
    panelDesc:
      'Estime el consumo de tinta CMYK en gramos a partir de una imagen o PDF de referencia, sin enviar datos al servidor.',
    section: {
      tag: 'Estimación',
      title: 'Estimar tintas desde archivo',
      subtitle:
        'Analice la cobertura CMYK promedio del archivo y proyecte el consumo en gramos por canal según el área de impresión.',
    },
    flow: {
      stepPlancha: 'Plancha',
      stepArchivo: 'Archivo',
      stepArea: 'Tamaño',
      stepResultado: 'Resultado',
    },
    hero: {
      title: 'Proyecte el consumo de tinta CMYK',
      hint: 'Seleccione la plancha, cargue el diseño y calcule gramos por canal según el despiece configurado en Corte de papel.',
    },
    pending: {
      plancha: 'Seleccione una plancha de preprensa para continuar.',
      archivo: 'Asocie un tipo de papel en Corte de papel para precargar medidas del despiece.',
      area: 'Cargue el archivo de referencia para confirmar el tamaño a imprimir.',
      resultado: 'Confirme ancho y alto, luego pulse «Calcular consumo de tinta».',
    },
    upload: {
      tag: 'Paso 2',
      title: 'Archivo de referencia',
      subtitle: 'Imagen o PDF del diseño a analizar. Las medidas de impresión no cambian al cargarlo.',
      hint: (maxMb: number) => `Imagen (JPG, PNG, WEBP, GIF) o PDF · máx. ${maxMb} MB`,
      lockedSinRegistrosTitle: 'Sin registros de plancha',
      lockedSinRegistrosHint:
        'Cree registros en Preprensa (Especificaciones técnicas) antes de cargar un archivo.',
      lockedTitle: 'Seleccione una plancha de preprensa',
      lockedHint: 'Complete el Paso 1 para habilitar la carga del archivo de referencia.',
      lockedSinTipoPapelTitle: 'Sin tipo de papel asociado',
      lockedSinTipoPapelHint:
        'Asocie un tipo de papel en Corte de papel para la plancha seleccionada antes de estimar tintas.',
      dropTitle: 'Arrastre un archivo o selecciónelo desde su equipo',
      dropActive: 'Suelte el archivo aquí',
      selectBtn: 'Seleccionar archivo',
      replaceBtn: 'Cambiar archivo',
      removeBtn: 'Quitar',
      editStoredPreviewHint:
        'Vista previa del registro guardado. Para recalcular, use «Cambiar archivo» y vuelva a cargar el diseño.',
      previewAlt: 'Vista previa del archivo cargado',
      pixelsLabel: (width: number, height: number) => `${width} × ${height} px`,
      pdfBadge: 'PDF',
      pdfPageLabel: (page: number, total: number) =>
        total > 1 ? `Página ${page} de ${total}` : 'Página 1',
      pdfSizeLabel: (widthCm: number, heightCm: number) =>
        `${widthCm.toFixed(1)} × ${heightCm.toFixed(1)} cm (tamaño PDF)`,
      colorProfileTitle: 'Propiedades de color en el archivo',
      colorSpaceLabel: 'Espacio de color',
      colorSpaceValues: {
        rgb: 'RGB',
        cmyk: 'CMYK',
        mixed: 'CMYK + spot (mixto)',
      },
      spotStatusFound: 'Placas Pantone (spot) detectadas en el PDF',
      spotStatusMissingPdf:
        'No se encontraron placas Pantone en el PDF. Solo se estimará tinta CMYK de proceso.',
      spotStatusMissingImage:
        'Las imágenes no incluyen metadatos Pantone. Suba el PDF de preprensa para detectar spots.',
      spotNamesLabel: 'Spots encontrados',
      spotReferencesLabel: (count: number) =>
        `${count.toLocaleString('es-CO')} referencia${count === 1 ? '' : 's'} de color para el cálculo Pantone.`,
      cmykNativeLabel: 'El PDF incluye valores CMYK nativos (DeviceCMYK).',
      spotChipFound: 'Pantone en archivo',
      spotChipMissing: 'Sin Pantone en archivo',
      colorSpaceChip: (label: string) => label,
    },
    plancha: {
      tag: 'Paso 1',
      title: 'Plancha de preprensa',
      subtitle: 'Elija la plancha de Preprensa. El resto de pasos se habilitan al completar cada selección.',
      label: 'Plancha',
      placeholder: 'Seleccione un registro de preprensa…',
      hint: 'Los valores provienen del registro de Preprensa seleccionado.',
      emptySinRegistros:
        'Aún no hay registros de plancha en Preprensa. Complete Especificaciones técnicas en Preprensa para habilitar esta sección.',
      tamanosBuenosLabel: 'Tamaños buenos',
      sobranteLabel: 'Sobrante',
      totalPliegosLabel: 'Total tamaños',
      totalPliegosHint: 'Tamaños buenos + sobrante',
      corteSectionTitle: 'Datos de corte de papel',
      corteSectionHint: 'Información definida en Corte de papel para la plancha seleccionada.',
      tipoPapelLabel: 'Tipo de papel',
      esmaltadoLabel: 'Esmaltado',
      esmaltadoSi: 'Sí',
      esmaltadoNo: 'No',
      despieceLabel: 'Despiece por pliego',
      corteEmpty: 'Complete tipo de papel y despiece en Corte de papel para esta plancha.',
      sinTipoPapelHint:
        'Asocie un tipo de papel en Corte de papel para habilitar archivo, área de impresión y consumo estimado.',
    },
    params: {
      tag: 'Paso 3',
      title: 'Tamaño a imprimir',
      subtitle: 'Confirme cuánto mide el diseño en cada pliego y calcule el consumo de tinta.',
      measuresGroupTitle: 'Medidas del despiece',
      advancedGroupTitle: 'Parámetros de cálculo',
      sizeQuestion: '¿Cuánto mide el diseño en el pliego?',
      advancedToggle: 'Opciones avanzadas (DPI y factor de conversión)',
      defaultsHint: 'Medidas ajustadas manualmente.',
      widthLabel: 'Ancho',
      heightLabel: 'Alto',
      measureUnit: 'cm',
      despieceSizeHint: (widthCm: number, heightCm: number) =>
        `Medidas del despiece: ${widthCm.toFixed(1).replace('.', ',')} × ${heightCm.toFixed(1).replace('.', ',')} cm. Corríjalas solo si no coinciden con lo que se imprimirá.`,
      despieceSizeEmpty:
        'Sin despiece en Corte de papel. Escriba ancho y alto del área que se imprimirá en cada pliego.',
      dpiLabel: 'Resolución (DPI)',
      dpiHint: '300 DPI es el estándar de preprensa offset en Colombia (Medellín y regionales).',
      conversionLabel: 'Factor de conversión',
      conversionHint:
        'Gramos por cm² al 100 % de cobertura. Referencia: 0,0002 ml/cm² × densidad 1,05 grm/ml. Calibre con tiraje real en gramos.',
      densityHint: 'Densidad tinta offset de referencia: 1,05 grm/ml.',
      factorHint: 'Valor de referencia offset: 0,00021 grm/cm² (0,0002 ml/cm² × densidad 1,05). Es un número pequeño, no cero.',
      factorUnit: 'grm/cm²',
      restoreDefaultFactor: (factor: string) => `Usar factor por defecto (${factor})`,
      restoreDefaultSuccess:
        'Factor restaurado. La estimación se recalculó con el valor de referencia offset.',
    },
    actions: {
      calculate: 'Calcular consumo de tinta',
      calculating: 'Calculando consumo…',
    },
    progress: {
      processingFile: 'Analizando archivo…',
      preparingSample: 'Preparando muestra del diseño…',
      renderingPdf: 'Renderizando PDF para análisis…',
      readingPixels: 'Leyendo píxeles del archivo…',
      detectingSpots: 'Detectando colores Pantone…',
      computingCmyk: 'Calculando cobertura CMYK…',
      detectingPantone: 'Clasificando tintas Pantone…',
      finishing: 'Finalizando estimación…',
    },
    entradas: {
      addTitle: 'Nueva estimación de tintas',
      editTitle: 'Editar estimación de tintas',
      addHint: 'Calcule el consumo y agregue el registro de esta plancha.',
      editHint: 'Ajuste parámetros, recalcule y guarde los cambios.',
      addButton: 'Guardar registro',
      saving: 'Guardando…',
      saveEdit: 'Guardar cambios',
      cancelEdit: 'Cancelar edición',
      edit: 'Editar',
      editing: 'Editando',
      remove: 'Eliminar',
      emptyTitle: 'Sin registros aún',
      emptyGlobal:
        'Aún no hay registros. Seleccione una plancha, calcule la estimación y agregue el registro.',
      emptyPlanchaSeleccionada:
        'Esta plancha aún no tiene registro. Calcule la estimación y pulse «Agregar registro».',
      planchaCompletaHint: 'Esta plancha ya tiene registro. Use Editar en la tabla para modificarlo.',
      pasoRegistros: 'Registros',
      tablePlancha: 'Plancha',
      tablePapelDespiece: 'Papel · Despiece',
      tableArchivo: 'Archivo',
      tableMedidas: 'Área de impresión',
      tablePliegos: 'Pliegos',
      tableConsumo: 'Consumo primarios (CMYK) · Pantone',
      tableTotalColorBasico: 'Total colores básicos',
      tableTotalPantone: 'Total Pantone',
      tableTotalUnificado: 'Total unificado',
      dpiValueLabel: (dpi: number) => `${dpi} DPI`,
      tableAcciones: 'Acciones',
    },
    resumen: {
      subtitle: (completados: number, total: number) =>
        `${completados} de ${total} plancha${total === 1 ? '' : 's'} con registro de estimación`,
      valorCian: 'Cian (C)',
      valorMagenta: 'Magenta (M)',
      valorAmarillo: 'Amarillo (Y)',
      valorNegro: 'Negro (K)',
      totalEstimadoPliego: 'Total estimado por pliego',
      totalEstimadoProcessPliego: 'Estimado CMYK por pliego',
      totalEstimadoPantonePliego: 'Estimado Pantone por pliego',
      totalEstimadoUnifiedPliego: 'Total estimado unificado por pliego',
      totalPedidoProcess: 'Total colores básicos',
      totalPedidoPantone: 'Total colores Pantone',
      total: 'Total tinta pedido unificado',
      totalHint: 'Consumo proyectado para cubrir el tiraje de las planchas con registro.',
      empty: '—',
    },
    calibration: {
      tag: 'Opcional',
      title: 'Calibrar con tiraje real',
      subtitle:
        'Compare lo estimado con lo medido en prensa. El sistema ajusta el factor de conversión, no solo el total mostrado.',
      measuredLabel: 'Consumo real medido en prensa (g total)',
      measuredHint:
        'Sume C + M + Y + K del tiraje en gramos. Con eso se calcula un factor nuevo para futuras estimaciones.',
      previewTitle: 'Vista previa del ajuste',
      currentFactorLabel: 'Factor actual',
      projectedFactorLabel: 'Factor ajustado',
      estimatedTotalLabel: 'Total estimado (factor actual)',
      measuredTotalLabel: 'Consumo medido',
      deviationLabel: 'Desviación estimado vs. medido',
      factorChangeLabel: 'Cambio del factor',
      appliedTitle: 'Calibración aplicada',
      appliedHint:
        'El factor de conversión quedó actualizado en «Tamaño a imprimir» y el consumo estimado se recalculó con ese valor.',
      apply: 'Recalcular con factor ajustado',
      applying: 'Recalculando…',
      requiresEstimate: 'Calcule primero una estimación antes de calibrar.',
      invalidMeasured: 'Ingrese el consumo medido en gramos (valor mayor a cero).',
      invalidCoverage: 'La cobertura de la imagen es insuficiente para calibrar.',
      invalidParams: 'Revise el área de impresión y el consumo medido.',
    },
    results: {
      tag: 'Paso 4',
      badge: 'CMYK · LIVE',
      title: 'Consumo estimado',
      subtitle: 'Cobertura promedio y peso estimado en gramos.',
      discardEstimate: 'Descartar cálculo',
      channelHeader: 'Canal',
      coverageHeader: 'Cobertura',
      weightHeader: 'Peso',
      totalLabel: 'Total estimado',
      processTotalLabel: 'Colores básicos (CMYK)',
      pantoneTotalLabel: 'Pantone',
      unifiedTotalLabel: 'Total unificado',
      processShortLabel: 'CMYK',
      pantoneShortLabel: 'Pantone',
      unifiedShortLabel: 'Total',
      totalPedidoLabel: 'Total tinta pedido',
      totalPedidoEmpty: 'Indique tamaños buenos en Preprensa para proyectar el total tinta pedido.',
      totalPedidoFormulaSummary: 'Ver fórmula de cálculo',
      calibrationDetailsSummary: 'Calibrar con tiraje real (opcional)',
      totalPedidoFormulaPliegosRule: 'Total tamaños = Tamaños buenos + Sobrante',
      totalPedidoFormulaPedidoRule: 'Total tinta pedido = (CMYK + Pantone por pliego) × Total tamaños',
      totalPedidoFormulaPliegosCalc: (
        tamanosBuenos: number,
        sobrante: number,
        totalPliegos: number
      ) =>
        `${tamanosBuenos.toLocaleString('es-CO')} + ${sobrante.toLocaleString('es-CO')} = ${totalPliegos.toLocaleString('es-CO')} tamaños`,
      totalPedidoFormulaPedidoCalc: (
        totalInkG: number,
        totalPliegos: number,
        totalPedidoG: number
      ) =>
        `${totalInkG < 0.01 ? totalInkG.toFixed(4) : totalInkG.toFixed(2)} grm × ${totalPliegos.toLocaleString('es-CO')} = ${totalPedidoG < 100 ? totalPedidoG.toFixed(2) : totalPedidoG.toFixed(1)} grm`,
      processColorsTitle: 'Colores de proceso (CMYK)',
      processColorsHint:
        'Cuadros con los primarios offset (C, M, Y, K). Los demás colores del diseño se descomponen en estas cuatricromías.',
      detectedColorsTitle: 'Pantone del archivo',
      empty: 'Cargue una imagen o PDF y pulse «Calcular estimación» para ver el desglose CMYK.',
    },
    channels: {
      c: 'Cian (C)',
      m: 'Magenta (M)',
      y: 'Amarillo (Y)',
      k: 'Negro (K)',
    },
    channelNames: {
      c: 'Cian',
      m: 'Magenta',
      y: 'Amarillo',
      k: 'Negro',
    },
    errors: {
      invalidType: 'Seleccione una imagen (JPG, PNG, WEBP, GIF) o un PDF.',
      maxSize: (maxMb: number) => `El archivo supera el tamaño máximo de ${maxMb} MB.`,
      imageLoadFailed: 'No se pudo cargar la imagen. Verifique que el archivo no esté dañado.',
      pdfLoadFailed: 'No se pudo leer el PDF. Verifique que el archivo no esté dañado o protegido.',
      invalidDimensions: 'La imagen no tiene dimensiones válidas.',
      canvasUnavailable:
        'No se pudo leer la imagen en el navegador. Intente con otro archivo o formato.',
      emptyImage: 'La imagen no tiene píxeles opacos para analizar.',
      invalidParams: 'Revise ancho, alto, DPI y factor de conversión (valores mayores a cero).',
      unknown: 'Ocurrió un error al estimar las tintas. Intente de nuevo.',
    },
  },
  conversionImagen: {
    panelDesc:
      'Conversión profesional RGB → CMYK en el navegador con Little CMS 2 (LCMS2) vía WebAssembly. Sin servidor.',
    section: {
      tag: 'Conversión',
      title: 'Conversión img',
      subtitle: 'RGB a CMYK con perfiles ICC, rendering intent y control de TAC para preprensa.',
    },
    flow: {
      stepArchivo: 'Archivo',
      stepOpciones: 'Opciones CMYK',
      stepResultado: 'Resultado',
    },
    pending: {
      archivo: 'Cargue una imagen RGB para habilitar las opciones de conversión.',
      opciones: 'Ajuste perfiles ICC, TAC y GCR, luego pulse «Convertir a CMYK».',
      wasm: 'Espere a que el motor LCMS2 esté listo antes de convertir.',
    },
    options: {
      title: 'Opciones de conversión',
      subtitle: 'Revise perfiles y parámetros. Los ajustes avanzados son opcionales.',
      groups: {
        profilesTitle: 'Perfiles de color',
        profilesHint: 'De dónde viene la imagen y hacia qué espacio CMYK va a convertir.',
        conversionTitle: 'Modo y archivo',
        conversionHint: 'Cómo mapear los colores y en qué formato guardar el resultado.',
        printTitle: 'Ajustes de imprenta (opcional)',
        printHint: 'TAC y GCR. Use los valores que le indique su proveedor.',
        printToggleHint: 'TAC y GCR',
        printToggleAction: 'Ver opciones',
        printToggleActionOpen: 'Ocultar',
      },
    },
    results: {
      title: 'Resultado CMYK',
      subtitle: 'Vista previa simulada en RGB y descarga en TIFF o PDF con perfil ICC embebido.',
    },
    help: {
      profilesSummary: 'Guía de perfiles RGB y CMYK',
      conversionSummary: 'Guía de modo y formato',
      printSummary: 'Guía de TAC y GCR',
      inputSummary: '¿Qué perfil RGB de entrada usar?',
      outputSummary: '¿Qué perfil CMYK de salida usar?',
      renderingIntentSummary: '¿Qué rendering intent elegir?',
      tacSummary: '¿Qué es TAC y qué porcentaje poner?',
      gcrSummary: '¿Qué nivel de GCR aplicar?',
      outputSummary: '¿Qué formato TIFF generar?',
    },
    progress: {
      decode: 'Leyendo imagen…',
      prepare: 'Preparando motor de color…',
      transform: 'Convirtiendo RGB → CMYK…',
      post: 'Aplicando TAC y GCR…',
      preview: 'Generando vista previa…',
      encode: 'Codificando TIFF CMYK…',
      pdf: 'Generando PDF CMYK…',
      queue: 'Iniciando conversión…',
      done: 'Finalizando…',
    },
    wasm: {
      initializing: 'Inicializando motor LCMS2 (WebAssembly)…',
      ready: 'Motor de color listo.',
      unsupported: 'Su navegador no soporta WebAssembly. Use Chrome, Firefox, Edge o Safari reciente.',
      initFailed: 'No se pudo cargar lcms-wasm. Recargue la página e intente de nuevo.',
    },
    upload: {
      title: 'Archivo de origen',
      subtitle: 'JPEG, PNG, WebP, BMP, GIF o TIFF en resolución original.',
      dropLabel: 'Arrastre una imagen o haga clic para seleccionar',
      dropActive: 'Suelte la imagen aquí',
      dropHint: 'La transparencia se aplana sobre blanco. Escala de grises se convierte automáticamente.',
      selectBtn: 'Seleccionar archivo',
      openingPicker: 'Abriendo explorador de archivos…',
      readingFile: 'Leyendo imagen…',
      replace: 'Cambiar archivo',
      remove: 'Quitar',
      previewAlt: 'Vista previa del archivo cargado',
      pixelsLabel: (width: number, height: number) => `${width.toLocaleString('es-CO')} × ${height.toLocaleString('es-CO')} px`,
    },
    profiles: {
      inputLabel: 'RGB de entrada',
      outputLabel: 'CMYK de salida',
      inputHelpIntro:
        'El perfil RGB indica cómo interpretar los colores de su imagen antes de pasarla a CMYK. Debe coincidir con el espacio en que fue creada o exportada la foto.',
      outputHelpIntro:
        'El perfil CMYK define cómo se separarán las tintas en imprenta. Elija el que le indique su proveedor (Europa, USA o GRACoL).',
      outputUnavailableNote: 'Perfil no instalado en public/icc/.',
      iccMissing:
        'No se encontró el perfil en public/icc/. Use el perfil CMYK genérico incluido o consulte public/icc/README.md.',
    },
    renderingIntent: {
      label: 'Modo de conversión',
      hint: 'Define cómo se mapean los colores fuera de la gama del destino CMYK.',
      helpIntro:
        'Cuando un color RGB no cabe en la gama CMYK, este ajuste decide qué priorizar: apariencia, exactitud o saturación.',
      perceptual: 'Perceptual',
      perceptualDesc: 'Fotografías e imágenes continuas. Mantiene la sensación visual aunque los valores exactos cambien.',
      relativeColorimetric: 'Relative Colorimetric',
      relativeColorimetricDesc: 'Logotipos, rótulos y colores corporativos. Respeta los tonos medios y planos con mayor fidelidad.',
      saturation: 'Saturation',
      saturationDesc: 'Gráficos llamativos y presentaciones. Conserva colores vivos aunque los detalles finos varíen.',
      absoluteColorimetric: 'Absolute Colorimetric',
      absoluteColorimetricDesc: 'Pruebas de color y control con imprenta. Compara con muestra física sin compensar el blanco del papel.',
    },
    tac: {
      label: 'TAC — Total Area Coverage',
      hint: 'Límite máximo de tinta (C+M+Y+K) por píxel. Couché 300–340 %, bond 260–280 %, digital 220–260 %.',
      helpIntro:
        'TAC = suma de C + M + Y + K en un mismo punto. Limita cuánta tinta total puede llevar un píxel para evitar manchas, repunte o sequedad lenta.',
      presetHelp: {
        digital: '240 % — prensas digitales y papeles que no admiten mucha tinta.',
        bond: '280 % — papeles bond, volantes y trabajos económicos.',
        coated: '320 % — couché offset habitual; buen punto de partida si la imprenta no indica otro valor.',
        max: '340 % — couché brillante con buen secado; confírmelo con la imprenta antes de usarlo.',
      },
      presets: {
        digital: 'Digital (240 %)',
        bond: 'Bond (280 %)',
        coated: 'Couché (320 %)',
        max: 'Máximo (340 %)',
      },
    },
    gcr: {
      label: 'GCR — Generación de negro',
      hint:
        'Simulación post-conversión. El perfil CMYK define el negro base; lcms-wasm no expone curvas GCR del RIP.',
      helpIntro:
        'GCR traslada gris de cian, magenta y amarillo hacia negro (K). Ahorra tinta de color y estabiliza neutros, pero depende también del perfil ICC y del RIP.',
      lightDesc: 'Poca sustitución. Útil si quiere conservar el máximo color en CMY.',
      mediumDesc: 'Opción equilibrada para la mayoría de trabajos comerciales.',
      maximumDesc: 'Más negro en sombras. Reduce CMY, pero conviene validar el resultado en imprenta.',
      light: 'GCR ligero',
      medium: 'GCR medio (estándar)',
      maximum: 'GCR máximo',
      limitation:
        'Para control GCR/UCR idéntico a Photoshop, el ajuste depende del perfil ICC de destino y del RIP de imprenta.',
    },
    output: {
      label: 'Formato de salida',
      helpIntro:
        'El TIFF conserva los cuatro canales CMYK y el perfil ICC embebido. El PDF usa DeviceCMYK y metadatos compatibles con Estimar tintas.',
      tiff16: 'TIFF CMYK 16-bit (recomendado)',
      tiff16Desc: 'Más tonos por canal; preferible para imprenta offset, retoques y archivos maestros.',
      tiff8: 'TIFF CMYK 8-bit (archivo más liviano)',
      tiff8Desc: 'Menor peso. Sirve para pruebas internas o cuando la imprenta acepta 8 bits.',
      jpegNote:
        'JPEG CMYK no está disponible en navegador sin backend. Use TIFF con perfil ICC embebido.',
    },
    preview: {
      label: 'Vista previa (simulación RGB)',
      hint:
        'Los monitores solo muestran RGB. La previsualización convierte CMYK → sRGB para aproximar el resultado; no sustituye una prueba en imprenta.',
      empty: 'Suba una imagen y pulse «Convertir a CMYK» para ver la simulación.',
    },
    actions: {
      convert: 'Convertir a CMYK',
      converting: 'Convirtiendo…',
      download: 'Descargar TIFF CMYK',
      downloadPdf: 'Descargar PDF CMYK',
      reset: 'Nueva conversión',
      cancel: 'Cancelar',
    },
    requirements: {
      title: 'Para activar la conversión:',
      file: 'Seleccione una imagen',
      wasm: 'Espere a que el motor LCMS2 esté listo',
      profile: 'Perfil CMYK disponible (integrado o en public/icc/)',
    },
    result: {
      sizeLabel: 'Tamaño TIFF',
      pdfSizeLabel: 'Tamaño PDF',
      dimensionsLabel: 'Dimensiones',
      alphaFlattened: 'Se detectó transparencia y se aplanó sobre blanco.',
      grayscaleConverted: 'Imagen en escala de grises convertida a RGB antes del perfilado.',
      tiffViewerNote:
        'El visor de fotos de Windows no abre TIFF CMYK. El PDF CMYK puede cargarse en Estimar tintas para estimar consumo de tinta.',
    },
    errors: {
      unsupportedFormat: 'Formato no soportado. Use JPEG, PNG, WebP, BMP, GIF o TIFF.',
      corruptImage: 'No se pudo leer la imagen. El archivo puede estar dañado.',
      iccMissing: 'Perfil ICC no encontrado. Coloque los archivos .icc en public/icc/.',
      iccInvalid:
        'El perfil ICC es inválido o está corrupto. Si descargó desde la web, compruebe que no sea una página HTML renombrada como .icc.',
      conversionFailed: 'Error durante la conversión. Intente con otra imagen o perfil.',
    },
    bundleNote:
      'lcms-wasm (~64 KB) se carga solo al abrir esta pestaña. wasm-vips (~8 MB) no es necesario para esta función.',
  },
} as const
