/** Textos de la sección Preprensa › Diseño */
export const PREPRENSA_DISENO_COPY = {
  acabados: {
    lineaTroquel: 'L\u00EDnea troquel',
    lineaTroquelDesc: 'Corte o perforado con troquel en l\u00EDnea de producci\u00F3n',
    reservaUv: 'Reserva UV',
    reservaUvDesc: 'Zona protegida para barniz o acabado UV selectivo',
    estampado: 'Estampado',
    estampadoDesc: 'Aplicaci\u00F3n de foil, relieve plano o estampado en fr\u00EDo',
    repuje: 'Repuje',
    repujeDesc: 'Relieve en alto o bajo sobre el sustrato impreso',
    summary: (selected: number) =>
      selected === 0 ? '' : `${selected} activo${selected === 1 ? '' : 's'}`,
  },
  sectionTags: {
    trabajo: 'Historial',
    identidad: 'Nombre',
    costo: 'Costo',
    archivo: 'PDF',
    especificaciones: 'T\u00E9cnico',
    acabados: 'Acabados',
    montaje: 'Montaje',
  },
  existente: {
    ariaLabel: 'Dise\u00F1o existente',
    clienteTitle: 'Cliente',
    trabajoTitle: 'Trabajo y Dise\u00F1o anterior del cliente',
  },
  nuevo: {
    ariaHistorial: 'Informaci\u00F3n del trabajo ya realizado',
    ariaNuevo: 'Configuraci\u00F3n del dise\u00F1o nuevo',
    tituloHistorial: 'Datos del trabajo anterior',
    tituloNuevo: 'Datos del dise\u00F1o nuevo',
    leadHistorial:
      'Revise la informaci\u00F3n importada y ajuste solo lo que cambie en esta orden.',
    panelBasicoTitulo: 'Informaci\u00F3n b\u00E1sica',
    panelProduccionTitulo: 'Producci\u00F3n',
    bannerTitulo: 'Trabajo de referencia',
    refDiseno: 'Dise\u00F1o',
    sinNombreDiseno: 'Sin nombre de dise\u00F1o',
    nombreLabel: 'Nombre del dise\u00F1o',
    nombrePlaceholder: 'Ej. Empaque caja premium 2026',
    pdfTitulo: 'Archivo PDF',
    pdfEmptyTitle: 'Subir dise\u00F1o en PDF',
    pdfEmptyHint: (maxMb: number) => `Solo PDF \u00B7 m\u00E1x. ${maxMb} MB`,
    pdfSelectBtn: 'Seleccionar archivo',
    pdfChangeBtn: 'Cambiar',
    pdfDropActive: 'Suelte el archivo aqu\u00ED',
    pdfHistorialHint: 'Archivo del trabajo anterior. Cargue uno nuevo si lo necesita.',
    pdfQuitar: 'Quitar',
    pdfPreview: (fileName: string) => `Vista previa: ${fileName}`,
    specsTitulo: 'Especificaciones t\u00E9cnicas',
    specsSubHistorial: 'Datos t\u00E9cnicos del trabajo anterior',
    acabadosTitulo: 'Acabados',
    acabadosSubtitle: 'Toque un acabado para activarlo o desactivarlo.',
    acabadosAria: 'Acabados del dise\u00F1o',
    montajeTitulo: 'Precio de montaje',
    costoDiseno: {
      ariaLabel: 'Costo del dise\u00F1o',
      opciones: {
        sinCosto: {
          title: 'Sin costo de dise\u00F1o',
          description: 'No se factura un valor aparte por crear el dise\u00F1o',
        },
        conCosto: {
          title: 'Cobrar dise\u00F1o',
          description: 'Indique el valor que se cobrar\u00E1 por el dise\u00F1o en esta orden',
        },
      },
      valorLabel: 'Valor a cobrar (COP)',
    },
    montaje: {
      ariaLabel: 'Precio de montaje',
      hint: 'Seleccione la tarifa del cat\u00E1logo. Elija \u00ABSin montaje\u00BB si no aplica.',
      selectLabel: 'Tarifa de montaje',
      selectPlaceholder: 'Elija una tarifa\u2026',
      sinMontajeOption: 'Sin montaje',
      empty: 'No hay tarifas de montaje activas en el cat\u00E1logo.',
      resumenLabel: 'Tarifa aplicada',
    },
  },
  coloresPlanchas: {
    tamanosBuenosFormula: 'Cantidad ÷ Cavidades (redondeo al entero más cercano)',
    tamanosBuenosNeedCavidades: 'Indique las cavidades para calcular los tamaños buenos.',
    tamanosBuenosNeedCantidad: 'Indique la cantidad para calcular los tamaños buenos.',
    faltaCavidad: 'Falta cavidades',
    faltaCantidad: 'Falta cantidad',
    validationTitle: 'Revise el registro',
    colorPickerPlaceholder: 'Cantidad de colores',
    colorPickerEditHint: 'Elija otra cantidad de colores para actualizar el registro.',
    sinPlanchasActivas: 'Sin tipos de plancha activos en el catálogo.',
    registro: {
      editing: 'Editando registro',
      edit: 'Editar registro',
      saveEdit: 'Guardar cambios',
    },
    validation: {
      selectColor: 'Seleccione un color de la lista.',
      selectPlancha: 'Seleccione el tipo de plancha.',
      detalleOpCantidad:
        'Registre la cantidad en Especificaciones › Detalle OP antes de agregar planchas.',
      numeroPlanchasSiete: 'Ingrese el número de planchas (7 o más).',
      numeroPlanchasColores: 'Seleccione la cantidad de colores de la lista.',
      numeroPlanchasMinimo: 'El número de planchas debe ser 7 o mayor.',
      cantidadRegistro: 'Ingrese la cantidad del registro.',
      descripcionRegistro: 'Ingrese la descripción del registro.',
      cavidadesRegistro: 'Ingrese el número de cavidades (mayor a cero).',
      detalleRegistro: 'Ingrese el detalle del registro.',
      registroDuplicado:
        'Ya existe un registro con el mismo tipo de plancha y la misma descripción o detalle.',
      historialSinPlancha: 'Seleccione el tipo de plancha del catálogo actual.',
      historialPlanchaInactiva: 'El tipo de plancha seleccionado ya no está activo en el catálogo.',
      historialSinObservacion: 'Ingrese una observación al actualizar este registro.',
    },
  },
  planchaSuministro: {
    ariaLabel: 'Quién suministra las planchas',
    tag: 'Suministro',
    title: 'Suministro de planchas',
    subtitle: 'Indique si las planchas las provee la empresa o el cliente',
    avisoCliente:
      'El cliente entrega las planchas: en este registro no se cobra precio de plancha.',
    precioNoAplica: 'No aplica (cliente suministra)',
    detalleClienteSuministraHint:
      'Se agrega al final «Cliente suministra plancha» y el tipo elegido.',
    resumenPlanchasCliente: 'Precio de planchas no incluido: cliente suministra.',
    totalPlanchasHintCliente: 'Sin cobro de planchas (cliente suministra)',
    opciones: {
      empresa: {
        title: 'Litografía suministra planchas',
        description: 'La empresa provee las planchas según catálogo y Preprensa',
      },
      cliente: {
        title: 'Cliente suministra planchas',
        description: 'El cliente entrega las planchas; no se cobra precio de plancha',
      },
    },
  },
  pdf: {
    soloPdf: 'Solo se permiten archivos PDF.',
    maxSize: (maxMb: number) => `El archivo no debe superar ${maxMb} MB.`,
    previewLoading: 'Generando vista previa…',
    previewError:
      'No se pudo mostrar la vista previa en este dispositivo. Puede abrir el archivo con el enlace.',
    previewOpen: (fileName: string) => `Abrir ${fileName}`,
    previewPagesHint: (total: number) =>
      `Vista previa: página 1 de ${total}. Use «Abrir» para ver el documento completo.`,
  },
} as const
