export const TERMINADOS_COPY = {
  asignacion: {
    desc: 'Asigne terminados del catálogo a cada plancha configurada en Corte de papel.',
    registro: {
      tag: 'Plancha',
      title: 'Plancha para terminado',
      subtitle: 'Seleccione la plancha con corte de papel configurado para asignar terminados.',
      label: 'Plancha',
      emptySinRegistros: 'Agregue registros en Preprensa y complételos en Corte de papel.',
      placeholder: 'Seleccione una plancha…',
      completo: 'Completado',
      hint: 'Un registro de terminados por plancha. Las planchas completadas se marcan en el listado.',
    },
    planchaDetalle: {
      zoneLabel: 'Datos del corte',
      sectionCorte: 'Corte de papel',
      sectionCorteHint: 'Valores configurados en Corte de papel para la plancha seleccionada.',
      tipoPapelHint: 'Definido en Corte de papel.',
      despieceHint: 'Despiece y medidas del registro seleccionado.',
      tamanosBuenosHint: 'Tamaños buenos del corte aplicados al cálculo de terminados.',
    },
    contexto: {
      tag: 'Contexto',
      title: 'Datos del corte',
      tipoPapel: 'Tipo de papel',
      despiece: 'Despiece seleccionado',
      tamanosBuenos: 'Tamaños buenos',
      incompleto: 'Complete tipo de papel, despiece y tamaños buenos en Corte de papel.',
    },
    selector: {
      tag: 'Catálogo',
      title: 'Terminados disponibles',
      quickAccess: 'Acceso rápido',
      quickAccessHint:
        'Los del catálogo con acceso directo en naranja. Los elegidos en el select permanecen en verde.',
      allLabel: 'Todos los terminados',
      placeholder: 'Seleccione un terminado…',
      add: 'Agregar terminado',
      duplicate: 'Este terminado ya está asignado a esta plancha.',
      emptyCatalog: 'No hay terminados en el catálogo.',
      planchaCompletaHint:
        'Esta plancha ya tiene terminados confirmados. Use Editar en la tabla para modificarlos.',
    },
    asignados: {
      tag: 'Asignados',
      title: 'Terminados vinculados',
      empty: 'Agregue terminados desde el catálogo o acceso rápido para armar el registro.',
      planchaCompletaHint:
        'No puede agregar más terminados a una plancha completada. Edite el registro existente si necesita cambios.',
      columns: {
        terminado: 'Terminado',
        despiece: 'Despiece',
        valorCmCuadrado: 'Valor cm²',
        tamanosBuenos: 'Tamaños buenos',
        costoMinimo: 'Costo mínimo',
        costoCalculado: 'Costo calculado',
        cobro: 'A cobrar',
        acciones: '',
      },
      crearRegistro: 'Crear registro',
      guardarRegistro: 'Guardar cambios',
      cancelEdit: 'Cancelar edición',
      remove: 'Quitar',
      subtotal: 'Subtotal borrador',
      cobroMinimoHint: 'Aplica costo mínimo',
      formula: {
        summary: 'Ver fórmula de cálculo',
        pasoCostoTitulo: 'Costo calculado',
        pasoCobroTitulo: 'Valor a cobrar',
        pasoTotalTitulo: 'Total a cobrar',
        costoCalculadoRule:
          'Costo calculado = redondeo al entero más cercano de (Ancho ÷ 100) × (Alto ÷ 100) × Valor cm² × Tamaños buenos',
        cobroRule:
          'Si el costo calculado es igual o mayor al costo mínimo del terminado en catálogo, el valor a cobrar es el costo calculado. Si es menor, se cobra el costo mínimo. Ambos valores se redondean al entero más cercano.',
        totalRule:
          'Total a cobrar = suma del valor a cobrar de todos los terminados confirmados',
        hint: 'Ancho y alto provienen del despiece del corte; tamaños buenos del mismo registro.',
      },
    },
    registros: {
      tag: 'Confirmados',
      title: 'Terminados asignados',
      pasoRegistros: 'Terminados asignados',
      emptyTitle: 'Sin terminados asignados',
      empty: 'Agregue terminados arriba y pulse «Crear registro» para confirmarlos aquí.',
      columns: {
        plancha: 'Plancha',
        terminado: 'Terminado',
        terminados: 'Terminados',
        valorCmCuadrado: 'Valor cm²',
        cobro: 'A cobrar',
        total: 'Total registro',
        acciones: 'Acciones',
      },
      edit: 'Editar',
      editing: 'Editando',
      remove: 'Eliminar',
      terminadoSingular: 'terminado',
      terminadoPlural: 'terminados',
      sinTerminados: 'Sin terminados en este registro',
    },
    resumen: {
      tag: 'Resumen',
      title: 'Resumen de terminado',
      totalLabel: 'Total a cobrar',
      totalHint: 'Suma de todos los terminados confirmados por plancha.',
      columns: {
        plancha: 'Plancha',
        cobro: 'A cobrar',
      },
    },
  },
} as const
