export const OPERATOR_WORK_COPY = {
  title: 'Mi trabajo',
  subtitle: 'Tus órdenes asignadas, listas para avanzar por proceso.',
  greeting: (name: string) => `Hola, ${name}`,
  loading: 'Cargando tus órdenes…',
  empty: {
    title: 'Sin órdenes asignadas',
    body: 'Cuando te asignen procesos en producción, aparecerán aquí para que puedas registrar avances y entregas.',
  },
  emptyFilter: {
    title: 'Nada en esta vista',
    body: 'Prueba otro filtro o limpia la búsqueda para ver más órdenes.',
  },
  searchPlaceholder: 'Buscar por orden, cliente o trabajo…',
  filters: {
    all: 'Todas',
    active: 'En proceso',
    pending: 'Pendientes',
    done: 'Completadas',
  },
  stats: {
    assigned: 'Asignadas',
    active: 'En proceso',
    pending: 'Pendientes',
    done: 'Completadas',
  },
  card: {
    open: 'Abrir orden',
    client: 'Cliente',
    yourProcesses: 'Tus procesos',
    delivery: 'Entrega',
    processes: 'Procesos',
    units: 'unidades',
    step: (current: number, total: number) => `${current} de ${total} procesos`,
    waiting: 'Esperando turno',
    nextUp: 'Siguiente paso',
    inProgress: 'En curso',
    completed: 'Completada',
  },
  breadcrumb: (name: string) => `IndiColors › Mi trabajo · ${name}`,
  sectionTitle: 'Órdenes asignadas',
  phasesLabel: 'Procesos asignados',
  currentProcess: (label: string) => `Proceso actual: ${label}`,
  kpi: {
    total: 'Cantidad total',
    completedProcesses: 'Pasaron todos los procesos',
    delivered: 'Entregado',
    deliverable: 'Saldo entregable',
    deliveryProgress: 'Avance de entrega',
    processProgress: 'completó procesos',
    laborTime: 'Tiempo laborado',
    laborTimeHint: 'Desde el inicio de la orden hasta finalizar todos los procesos asignados.',
  },
  table: {
    process: 'Proceso',
    total: 'Total',
    completed: 'Terminado',
    delivered: 'Entregado',
    pending: 'Pendiente',
    status: 'Estado / Actualizar',
    sectionBase: 'Procesos base',
    sectionTerminados: 'Terminados',
    sectionAcabados: 'Operaciones de acabado',
  },
  status: {
    pending: 'Pendiente',
    inProcess: 'En proceso',
    done: 'Terminado',
    blocked: 'Bloqueado',
  },
  actions: {
    startProcess: 'En proceso',
    registerUnits: 'Registrar avance',
    registerDelivery: 'Entrega parcial',
    save: 'Guardar',
    notePlaceholder: 'Nota del cambio de estado (opcional)',
    unitsPlaceholder: 'Cantidad',
  },
  deliveryHistory: {
    title: 'Historial de entregas y avances',
    empty: 'Sin entregas registradas aún.',
    entry: (process: string, units: number, at: string) =>
      `${process}: ${units.toLocaleString('es-CO')} u · ${at}`,
  },
  alerts: {
    noDeliverable: 'Sin saldo entregable aún',
    bottleneck: (process: string) => `Cuello de botella: ${process}`,
    processesPassed: (units: number, total: number) =>
      `${units.toLocaleString('es-CO')} de ${total.toLocaleString('es-CO')} unidades pasaron todos los procesos`,
    prerequisite: (process: string) =>
      `Debe completar unidades en el proceso anterior (${process}) antes de procesar más aquí.`,
    deliveryBlocked: 'No hay unidades procesadas pendientes de entrega en este proceso.',
    orderComplete: (duration: string) =>
      `Orden finalizada. Tiempo laborado neto: ${duration}.`,
  },
  workspace: {
    orderMeta: (client: string, date: string, total: string) =>
      `Cliente: ${client} · ${date} · Total: ${total} unidades`,
    deliveryLegend: 'Morado: procesos completados · Verde: entregado',
    currentProcessTitle: (label: string) => `Proceso actual: ${label}`,
    laborOrder: 'Tiempo laborado (orden)',
    laborProcess: 'Tiempo neto',
    pausedProcess: 'Tiempo en pausa',
    pauseCount: 'Paradas',
    pauseNow: 'Trabajo en pausa',
    pauseHistory: 'Ver paradas',
    noPauses: 'Sin paradas registradas',
    registerPause: 'Pausar',
    registerResume: 'Reanudar',
    pauseReason: 'Motivo de parada',
    quickAdd: 'Sumar rápido',
    remaining: 'Pendiente en este proceso',
    updateStatus: 'Actualizar avance',
    notAssigned: 'Proceso asignado a otro operador',
    timelineTitle: 'Actividad reciente',
    timelineEmpty: 'Aún no hay avances ni entregas en esta orden.',
    timelineProgress: 'Avance',
    timelineDelivery: 'Entrega parcial',
    timelinePause: 'Parada',
    timelineResume: 'Reanudación',
  },
  validation: {
    noteRequired: 'Agregue una nota para este cambio de estado.',
  },
} as const
