export const TRAZABILIDAD_COPY = {
  title: 'Trazabilidad por operario',
  subtitle:
    'Consulte inicio y fin de cada sesión, tiempos netos de trabajo y el detalle de paradas con su motivo.',
  searchPlaceholder: 'Buscar orden, operario, cliente o etapa…',
  filters: {
    title: 'Filtros',
    user: 'Operario',
    userAll: 'Todos',
    phase: 'Etapa',
    phaseAll: 'Todas',
    from: 'Desde',
    to: 'Hasta',
    orderStatus: 'Estado orden',
    orderStatusAll: 'Todos',
    clear: 'Limpiar filtros',
  },
  kpi: {
    sesiones: 'Sesiones',
    sesionesActivas: 'Activas ahora',
    tiempo: 'Tiempo neto',
    pausado: 'Tiempo en pausa',
    paros: 'Paradas registradas',
    unidades: 'Unidades procesadas',
    parciales: 'Entrega parcial',
  },
  results: {
    one: '1 sesión encontrada',
    many: (n: number) => `${n.toLocaleString('es-CO')} sesiones encontradas`,
  },
  card: {
    startedAt: 'Inicio',
    endedAt: 'Fin',
    inProgress: 'En curso',
    pausedNow: 'En pausa ahora',
    statusChangeAt: 'Último cambio',
    laborTime: 'Tiempo neto',
    pausedTime: 'Tiempo en pausa',
    pauseCount: 'Paradas',
    processedUnits: 'Procesadas',
    partialUnits: 'Entrega parcial',
    pauseHistory: 'Historial de paradas',
    noPauses: 'Sin paradas registradas en esta sesión.',
    pauseOpen: 'Parada activa',
    pauseClosed: 'Parada finalizada',
  },
  actions: {
    registerPause: 'Registrar parada',
    registerResume: 'Reanudar trabajo',
    registerPartial: 'Entrega parcial',
    registerProgress: 'Registrar avance',
    openOrder: 'Ver orden',
  },
  modal: {
    partialTitle: 'Registrar entrega parcial',
    progressTitle: 'Registrar cantidad procesada',
    pauseTitle: 'Registrar parada del proceso',
    resumeTitle: 'Reanudar trabajo',
    partialHint: 'Indique cuántas unidades entrega parcialmente en esta etapa.',
    progressHint: 'Indique cuántas unidades procesó el operario en esta sesión.',
    pauseHint: 'Seleccione el motivo por el cual se detuvo el trabajo en esta orden.',
    resumeHint: 'Confirme que el operario retoma el trabajo en esta etapa.',
    unitsLabel: 'Unidades',
    reasonLabel: 'Motivo de la parada',
    noteLabel: 'Nota (opcional)',
    noteRequiredLabel: 'Detalle (obligatorio si el motivo es Otro)',
    save: 'Guardar registro',
    cancel: 'Cancelar',
  },
  empty: {
    title: 'Sin sesiones para mostrar',
    body: 'No hay registros con los filtros actuales. Pruebe ampliar el rango de fechas o quitar filtros.',
  },
  loading: 'Cargando trazabilidad…',
} as const
